### ISSUE TITLE
Module["setWindowTitle"] -> setWindowTitle

### ISSUE THREAD

**Issue by nickwebha** [emscripten-core/emscripten#13568]
With the latest version of Emscripten (v2.0.14) I am getting the following error when run in the browser:
_Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)_

Emscripten is outputting:
```
if (typeof Module["setWindowTitle"] !== "undefined") {
 Module["setWindowTitle"](UTF8ToString($0));
}
```

when my understanding from the [changelog](https://emscripten.org/docs/introducing_emscripten/release_notes.html) (v1.38.40) is it should now be something like

```
if (typeof setWindowTitle !== "undefined") {
 setWindowTitle(UTF8ToString($0));
}
```

When I manually make the change the error goes away and everything runs fine.

Here is the command I am running:
```
em++																																						\
	-o "distribution/main.js"																															\
	client/main.cpp																																			\
	client/lib/web/libUrho3D.a																																\
	-std=c++17																																				\
	-Wall -Werror																																			\
	-Iinclude/ -Iclient/include/ -I/home/nick/Urho3D/build.web/include/																						\
	-g4 --source-map-base "/"																																\
	--preload-file "client/Data.pak" --preload-file "client/CoreData.pak" --no-heap-copy																	\
	--profiling -msse -msse2 -msimd128 --bind																												\
	-Wcast-align -Wover-aligned																																\
	-Wno-pthreads-mem-growth -Wno-overloaded-virtual																										\
	-s ALLOW_MEMORY_GROWTH=1 -s WASM_MEM_MAX=1GB -s WASM=1																									\
	-s ASSERTIONS=2 -s SAFE_HEAP=0 -s STACK_OVERFLOW_CHECK=2 -s DEMANGLE_SUPPORT=1																			\
	-s DISABLE_EXCEPTION_CATCHING=0																															\
	-s USE_PTHREADS=1																																		\
	-s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -s USE_OGG=1 -s USE_VORBIS=1 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='[ "png" ]'						\
	-s EXTRA_EXPORTED_RUNTIME_METHODS='[ "ccall", "cwrap" ]'																								\
	-s EXPORTED_FUNCTIONS='[ "_main" ]'																														\
	-s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=0																										\
	-O0
```

**Comment by kripken** [comment]
Where is that code (in your first quoted code) coming from? It does look like it needs to be updated, but I don't see it on emscripten trunk.

**Comment by nickwebha** [comment]
It is output as part of _main.js_.

**Comment by kripken** [comment]
Yes, but I don't think it is coming from emscripten. It might be a `--pre-js` (but I don't see one in your command) or an `EM_ASM` in your project?

**Comment by kripken** [comment]
I do see similar code in SDL2. SDL2 has been updated to the new format, so perhaps you are using an old-enough emscripten that still users an older SDL2?

(And that code indeed arrives from an EM_ASM in SDL2)

**Comment by sbc100** [comment]
Strange... emscripten upgrades should clear the cache where SDL2 lives so it should be impossible to have an older version in there.

Can you try `./embuilder build sdl2 --force` to force an update of the SDL2 library in the cache?

**Comment by nickwebha** [comment]
The only EM_ASM in my code is as follows:
```
EM_ASM(
	websocketJavascriptConnect();
	websocketJavascriptListeners();
);
```
As you can probably guess by the names, `websocketJavascriptConnect()` is a single line that connects a WebSocket and `websocketJavascriptListeners()` setups up callbacks to listen for messages.

There is no `--pre-js`.

**Comment by sbc100** [comment]
As @kripken said this code is coming from an old version SDL2 somehow.     It looks like it was fixed in the emscripten port back about a year ago: https://github.com/emscripten-ports/SDL2/commit/952f889879ba3d934249fc7d93b992f91f75a5cd

This was then rolling into emscripten soon after: #10931

Can you run `./embuilder build sdl2 --force` and make sure it says its downloading version_22.zip?

I

**Comment by nickwebha** [comment]
Sorry, I misread.

`./embuilder build sdl2 --force` gives me
```
embuilder:INFO: building and verifying sdl2
cache:INFO: deleting cached file: /home/nick/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2.a... (this will be cached in "/home/nick/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a" for subsequent builds)
cache:INFO:  - ok
embuilder:INFO: ...success
```

I do not see any version number(s) in that output.

**Comment by nickwebha** [comment]
For giggles I did mcc `--clear-cache`, `./embuilder build sdl2 --force`. I got:
```
shared:INFO: (Emscripten: Running sanity checks)
embuilder:INFO: building and verifying sdl2
system_libs:INFO: retrieving port: sdl2 from https://github.com/emscripten-ports/SDL2/archive/version_22.zip
system_libs:INFO: unpacking port: sdl2
cache:INFO: generating port: sysroot/lib/wasm32-emscripten/libSDL2.a... (this will be cached in "/home/nick/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2.a" for subsequent builds)
cache:INFO: generating system headers: sysroot_install.stamp... (this will be cached in "/home/nick/emsdk/upstream/emscripten/cache/sysroot_install.stamp" for subsequent builds)
cache:INFO:  - ok
cache:INFO:  - ok
embuilder:INFO: ...success
```
Seems like it is grabbing version 22.

I am only using `-s USE_SDL=2`, no other method (truth be told I do not know of any other methods). See command in my first post.

`grep setWindowTitle cache/ports/sdl2/SDL2-version_22/ -r` gives me
```
cache/ports/sdl2/SDL2-version_22/src/video/emscripten/SDL_emscriptenvideo.c:      if (typeof setWindowTitle !== 'undefined') {
cache/ports/sdl2/SDL2-version_22/src/video/emscripten/SDL_emscriptenvideo.c:        setWindowTitle(UTF8ToString($0));
```
so that looks fine.

`grep setWindowTitle cache/sysroot/lib/wasm32-emscripten/*` gives me
`Binary file cache/sysroot/lib/wasm32-emscripten/libSDL2.a matches`
so that looks fine.

**Comment by sbc100** [comment]
OK but you are still seeing `if (typeof Module["setWindowTitle"] !== "undefined") ` in your output JS somehow?

Somehow there is some EM_ASM or EM_JS function that must be injecting that code which happens to look just like the code from the old version of SDL.

Can you post your full link command?

Also if you build with EMCC_DEBUG=1 you should at least see the EM_ASM strings in the output of wasm-emscripten-finalize (although it doesn't tell you which object file each of them came from sadly.

**Comment by nickwebha** [comment]
Still seeing `Module["setWindowTitle"]` (just rebuilt the entire cache that was cleared before).

Now we are starting to get in a little over my head. I rely on em++ to do the linking (and all other steps) for me. How can I get the full link command?

With EMCC_DEBUG=1 I do see references to all the `EM_JS` and `EM_ASM` contents I am using. Just one of each, in my case:
```
EM_JS( void, websocketJavascriptSetMessageOutbound, ( const char* name, const char* data ), {
	websocketJavascriptGetMessageOutbound( UTF8ToString( name ), UTF8ToString( data ) );
} );
```
```
EM_ASM(
	websocketJavascriptConnect();
	websocketJavascriptListeners();
);
```

**Comment by sbc100** [comment]
You don't see `Module["setWindowTitle"]` in the output of `EMCC_DEBUG=1` at all?

That is super weird.

In the resulting JS can you show where `Module["setWindowTitle"]`  appears?  (i.e. can you post the context or better still the entire file?).


(The full link line (wasm-ld) is shown as part of `EMCC_DEBUG=1`, or you can get a more limited output that also includes it by adding `-v` to your `em++` command line).

**Comment by nickwebha** [comment]
Nor with `EMCC_DEBUG=2`.

[Here](https://github.com/emscripten-core/emscripten/files/6079279/main.js.zip) is the entire file. It just appears in just those two adjacent spots I mentioned (plus the line warning it was moved).

**Comment by sbc100** [comment]
So I see this inside of `ASM_CONSTS`:

```
 470762: function($0) {                                                          
  if (typeof Module["setWindowTitle"] !== "undefined") {                            
   Module["setWindowTitle"](UTF8ToString($0));                                                                             
  }                                                                              
  return 0;                                                                      
 }, 
```

This means that for sure its coming from an EM_ASM block, and almost certainly SDL2 (whose other asm blocks I also see).

So... WTF is going on?  :)

My best guess:  You are linking agsinst some old/fixed version of libSDL2 that is not in your cache.

Can you post the full output of you like with `EMCC_DEBUG=1`?EMCC_DEBUG=1

(how is it that you don't see all the EM_ASM blocks from SDL2 in the output of EMCC_DEBUG=1... anything that ends up in ASM_CONSTS in the js file should show up in output of wasm-emscripten-finalize which gets printed with EMCC_DEBUG.. I don't get why you only see two EM_ASM/EM_JS contents but the JS has many many more?)

**Comment by kripken** [comment]
One simple thing to check could be to grep for the old string on the entire drive. Somehow, an old SDL2 copy is being used, the only question is where.

And maybe it is being linked in not from the cache as @sbc100 said. it could be passed on the commandline or some other way.

**Comment by nickwebha** [comment]
[Here](https://github.com/emscripten-core/emscripten/files/6079394/EMCC_DEBUG.txt.zip) is the debug information.

I have grep'ed my entire filesystem from root making sure to escape the appropriate characters. The only place it was found was in the _main.js_ file I just sent you earlier (so nowhere). If memory serves I do not even think SDL has been updated since I installed the OS on here.

Mysteries abound! I assume no one else has reported this? If not I assume my installation just got zoinked somehow.

Got another wrench for you: I just installed a fresh VM (Ubuntu 20.04, same I am running on the host) and tested it there. The only thing the host and VM share is my programs source code (not SDL, not Emscripten install files). It is still doing the same thing.

**Comment by sbc100** [comment]
I do see this in the output of EMCC_DEBUG:

```
               '470762': "{ if (typeof Module['setWindowTitle'] !== "               
                         "'undefined') { "                                       
                         "Module['setWindowTitle'](UTF8ToString($0)); } return "                                           
                         '0; }',   
```

This must be coming from:

`/home/nick/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2-mt.a`

Can you strings to see what is in there. e.g: for me:

```
$ strings ../emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libSDL2-mt.a | grep setWin
{ if (typeof setWindowTitle !== 'undefined') { setWindowTitle(UTF8ToString($0)); } return 0; }
```

**Comment by nickwebha** [comment]
That returned
`_{ if (typeof setWindowTitle !== 'undefined') { setWindowTitle(UTF8ToString($0)); } return 0; }`

Looks fine.

**Comment by sbc100** [comment]
What about strings on libUrho3D.a?   Has that library somehow includes a copy of libSDL2 perhaps?

**Comment by nickwebha** [comment]
`strings libUrho3D.a | grep setWindowTitle` returned
`s{ if (typeof Module['setWindowTitle'] !== 'undefined') { Module['setWindowTitle'](UTF8ToString($0)); } return 0; }`

I also ran a `grep` on the Urho3D source tree (cloned from Github). Came up with this:
```
Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c:351:      if (typeof Module['setWindowTitle'] !== 'undefined') {
Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c:352:        Module['setWindowTitle'](UTF8ToString($0));
```

Not sure why this did not show up when I `grep`ed root before. Maybe I made a type-o and did not escape something?

So [there it is](https://github.com/urho3d/Urho3D/blob/master/Source/ThirdParty/SDL/src/video/emscripten/SDL_emscriptenvideo.c#L351).

**Comment by sbc100** [comment]
Phew!

Hopefully this issue can now be closes?

**Comment by nickwebha** [comment]
I think so! I will leave closing to you to make sure a fix does not get lost in the shuffle.

Thanks for all your help.
