### ISSUE TITLE
Optional chaining operator does not compile

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [emscripten-core/emscripten#15827]
This does not compile:

```
#include <emscripten.h>

int main() {
	EM_ASM({
		console?.log("");
	});
}
```

Error message:
```
/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8327
        var ret = node != null ? MOZ_TO_ME[node.type](node) : null;
                                                     ^

TypeError: MOZ_TO_ME[node.type] is not a function
    at from_moz (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8327:54)
    at Object.ExpressionStatement (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:7468:23)
    at from_moz (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8327:54)
    at Array.map (<anonymous>)
    at Object.From_Moz_BlockStatement [as BlockStatement] (eval at map (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8313:21), <anonymous>:7:14)
    at from_moz (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8327:54)
    at Object.FunctionExpression (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:7452:44)
    at from_moz (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8327:54)
    at Object.Property (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:7500:28)
    at from_moz (/Volumes/SSD/git/emsdk/upstream/emscripten/third_party/terser/terser.js:8327:54)
emcc: error: '/Volumes/SSD/git/emsdk/node/14.15.5_64bit/bin/node /Volumes/SSD/git/emsdk/upstream/emscripten/tools/acorn-optimizer.js /var/folders/4c/w1bj9h4d5_df436ckn8xxmqr0000gq/T/emscripten_temp_h10gr7ju/main_temp.js AJSDCE minifyWhitespace' failed (returned 1)
```

This might be related to other problems with terser: #13297, #12410

**Version of emscripten/emsdk:**
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.0.0 (3fd52e107187b8a169bb04a02b9f982c8a075205)
clang version 14.0.0 (https://github.com/llvm/llvm-project 4348cd42c385e71b63e5da7e492172cff6a79d7b)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /Volumes/SSD/git/emsdk/upstream/bin
```

**Failing command line in full:**
```
emcc -O3 main.cpp -o main_temp.js

**Comment by mmarczell-graphisoft** [comment]
@sbc100 might this also be fixed by the recent terser update?

**Comment by sbc100** [comment]
Yup!  Looks like this works now.  Thanks for following up.

**Comment by sbc100** [comment]
Nope, I spoke to soon.  Seems to still be an issue.

**Comment by sbc100** [comment]
Looks like the version of terser we updated to still doesn't support `ChainExpression`

**Comment by dholl** [comment]
This just bit me as well.  I was inspired by this sample code [from here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices):
```
if (!navigator.mediaDevices?.enumerateDevices) {
    console.log("enumerateDevices() not supported.");
}
```

My code was compiling & running with Debug or RelWithDebInfo builds, but my Release build was failing during the link stage with the same cryptic error:
```
/home/somewhere/emsdk/upstream/emscripten/third_party/terser/terser.js:21475
          var ret = node != null ? MOZ_TO_ME[node.type](node) : null;
                                                       ^
TypeError: MOZ_TO_ME[node.type] is not a function
```

When I instrumented terser.js file to print out node.type, I found "ChainExpression", and after figuring out what a ChainExpression was, I replaced the ```?.``` in my code to get Release builds working again.

So, I'm happy for now and very appreciative of the work put into emscripten, but it took a while to figure out that optimized release builds are allergic to ```?.```.
