### ISSUE TITLE
Asyncify+embind: Async operations do not finish ("Cannot have multiple async operations in flight at once")

### ISSUE THREAD

**Issue by Ghabry** [emscripten-core/emscripten#16291]
Hello,

the second time I call a function provided by embind from Javascript I get an abort "Cannot have multiple async operations in flight at once".

```
-s ALLOW_MEMORY_GROWTH=1 -s ASYNCIFY -s ASYNCIFY_IGNORE_INDIRECT -s MODULARIZE=1 --bind
```

embind code:

```cpp
	emscripten::class_<Emscripten_Interface>("api")
		.class_function("requestReset", &Emscripten_Interface::Reset)
		.class_function("downloadSavegame", &Emscripten_Interface::DownloadSavegame)

bool Emscripten_Interface::DownloadSavegame(int slot) {
	return true;
}
```

Calling ``api.downloadSavegame`` twice crashes with the mentioned abort.
The first time I get a promise returned that is always "pending" and never resolved.

Any idea what I'm doing wrong?

**Comment by iboukris** [comment]
Hi, I was about to report the exact same issue, getting this error for a non-async function:

```cpp
#include <emscripten/val.h>
#include <emscripten/bind.h>
#include <stdio.h>

using namespace emscripten;

static int getAnswer(val obj) {
    val result = obj.call<val>("asyncFetch").await();
    return result.as<int>();
}

static void sync() { setenv("ABC", "XYZ", 1); }

EMSCRIPTEN_BINDINGS(answerMachine) {
    emscripten::function("getAnswer", &getAnswer);
    emscripten::function("sync", &sync);
}
```
Compiled with:
```
emcc example.cpp --bind -s ASYNCIFY -s MODULARIZE=1 -s ASYNCIFY_DEBUG
```
And used with this javascript:

```javascript
const getModule = require('./a.out.js');
async function run () {
    let Module = await getModule();
    let answer = Module.getAnswer({'asyncFetch' :  async () => 42 });
    Module.sync();
    console.log(answer instanceof Promise);
    let data = await answer;
    console.log(data);
};
run();
```
When run with node it results:
```
node example.js
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: handleSleep 0
ASYNCIFY: maybe stop unwind [ 'dynCall_iii' ]
ASYNCIFY: start unwind 5247016
ASYNCIFY: maybe stop unwind [ 'dynCall_iii' ]
ASYNCIFY: maybe stop unwind []
ASYNCIFY: stop unwind
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
Aborted(Assertion failed: Cannot have multiple async operations in flight at once)
/home/admin/git/webgss/a.out.js:190
      throw ex;
      ^

RuntimeError: Aborted(Assertion failed: Cannot have multiple async operations in flight at once)
    at abort (/home/admin/git/webgss/a.out.js:1545:11)
    at assert (/home/admin/git/webgss/a.out.js:738:5)
    at Object.whenDone (/home/admin/git/webgss/a.out.js:2357:9)
    at Object.sync (eval at new_ (/home/admin/git/webgss/a.out.js:2227:27), <anonymous>:10:37)
    at run (/home/admin/git/webgss/example.js:5:12)
```
Note that if I compile with -O3 as recommended, then the behavior is even weirder and the last print out is missing.
```
node example.js
ASYNCIFY: maybe stop unwind []
ASYNCIFY: handleSleep 0
ASYNCIFY: maybe stop unwind [ 'B' ]
ASYNCIFY: start unwind 5247000
ASYNCIFY: maybe stop unwind [ 'B' ]
ASYNCIFY: maybe stop unwind []
ASYNCIFY: stop unwind
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
true
ASYNCIFY: start rewind 5247000
ASYNCIFY: maybe stop unwind []
ASYNCIFY: start: [Function (anonymous)]
ASYNCIFY: handleSleep 2
ASYNCIFY: stop rewind
ASYNCIFY: maybe stop unwind [ 'B' ]
ASYNCIFY: maybe stop unwind [ 'B' ]
ASYNCIFY: maybe stop unwind []
```
I was about to report it as a bug since the second call isn't async, that said this quit a limitation even for async calls, I wonder if this is a technical limitation or just needs to be worked on.

CC:  @RReverser

**Comment by Ghabry** [comment]
Thanks for confirming that this is not a bug in my code.

A solution I would be fine with is something like this policy (3rd argument to bind) ``allow_raw_pointers()``.

Call it e.g. ``is_sync()``. When this policy is set then the invocation will not return a promise because it is synchronized. (Well and abort if it wants to yield)

**Comment by kripken** [comment]
Side note, is this specific to embind? That assertion "cannot have multiple async operations in flight at once" is not embind-specific which is why I ask.

**Comment by iboukris** [comment]
Not sure, the closer I get with 'ccall' is this:

```c
#include <emscripten.h>

int myAsync() {
    emscripten_sleep(0);
    return 42;
}

int mySync() { return -1; }
```

Compiled with:

```
emcc -O0 example.c -s ASYNCIFY -s MODULARIZE=1 -s ASYNCIFY_DEBUG -s EXPORTED_FUNCTIONS=_myAsync,_mySync -s EXPORTED_RUNTIME_METHODS=ccall
```

The example.js:

```javascript
const getModule = require('./a.out.js');
async function run () {
    let Module = await getModule();
    let answer = Module.ccall("myAsync", "number", [], [], {async: true});
    Module._mySync();
    let sync = Module.ccall("mySync", "number");
    console.log(answer instanceof Promise);
    console.log(sync instanceof Promise);
    let data = await answer;
    console.log(data);
};
run();
```

Results:
```
node example.js 
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: handleSleep 0
ASYNCIFY: maybe stop unwind [ 'myAsync' ]
ASYNCIFY: start unwind 5244440
ASYNCIFY: maybe stop unwind [ 'myAsync' ]
ASYNCIFY: maybe stop unwind []
ASYNCIFY: stop unwind
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
ASYNCIFY: maybe stop unwind []
Aborted(Assertion failed: The call to mySync is running asynchronously. If this was intended, add the async option to the ccall/cwrap call.)
/home/admin/git/webgss/a.out.js:184
      throw ex;
      ^

RuntimeError: Aborted(Assertion failed: The call to mySync is running asynchronously. If this was intended, add the async option to the ccall/cwrap call.)
    at abort (/home/admin/git/webgss/a.out.js:1539:11)
    at assert (/home/admin/git/webgss/a.out.js:732:5)
    at Object.ccall (/home/admin/git/webgss/a.out.js:802:5)
    at run (/home/admin/git/webgss/example.js:6:23)

**Comment by iboukris** [comment]
If I call `mySync` with `async:true` then I get the in-flight err, but that might be intended.

**Comment by kripken** [comment]
Do you get the "in-flight error" when there is actually another pause still in progress?

Reading the code, I think this patch might help - please test if you can:

https://github.com/emscripten-core/emscripten/commit/db1bc260902f4a4656c46c9517fd15555cfa2cb8

**Comment by iboukris** [comment]
> Do you get the "in-flight error" when there is actually another pause still in progress?

I didn't change the mySync function, only the ccall invocation so I think not - if that's what you mean.

> Reading the code, I think this patch might help - please test if you can:

Doesn't seem to change the original Embind example error.

**Comment by iboukris** [comment]
>> Reading the code, I think this patch might help - please test if you can:
> Doesn't seem to change the original Embind example error.

The patch does however seem to fix the ccall example, but with `-O3` I now yields:
```
ReferenceError: asyncMode is not defined
    at Object.ccall (/home/admin/git/emscripten/a.out.js:9:4750)
    at run (/home/admin/git/emscripten/e.js:6:23)

**Comment by RReverser** [comment]
I think the problem is more with the imprecise error message, because code like

```js
const getModule = require('./a.out.js');
async function run () {
    let Module = await getModule();
    let answer = Module.getAnswer({'asyncFetch' :  async () => 42 });
    Module.sync();
    console.log(answer instanceof Promise);
    let data = await answer;
    console.log(data);
};
run();
```

is still dangerous because it performs re-entrancy into Wasm module while it's suspended by Asyncify. That is, Wasm module might have already temporarily changed some globals and "paused", and entering it again during this phase can lead to memory corruption of global variables / state, and very hard-to-debug issues.

So the error messages try to stop you from doing that and encourage you to finish the previous call before you start a new one.

**Comment by iboukris** [comment]
> I think the problem is more with the imprecise error message, because code like

Looking at the asyncify doc, it should be fixed as well in that case, quote: "It is not safe to start an async operation while another is already running. The first must complete before the second begins."

Can't speak for the OP, but for me async calls are as important and I find it too-bad they can't work as that would allow using asyncify as a drop-in replacement for network callbacks. IMO well written applications avoid globals due to threads, so maybe it could be allowed as an opt-in option or something.

That said, the behavior with `-O3` where the code is ignored should probably be fixed to throw as well.

**Comment by RReverser** [comment]
Looking at examples, generally I understand the desire to make parallel async calls, that would be really neat for performance reasons, but that's not really what Asyncify is for. It's intended for magically allowing synchronous C program pause from time to time to wait for an async result, not for magically making it re-entrant where it wasn't.

For proper async integration Emscripten would need to implement something like [`co_await`](https://en.cppreference.com/w/cpp/keyword/co_await)<->Promise integration in the future. Or maybe something like that is already possible with Asyncify coroutines? I'm not familiar with that part of the API.

**Comment by iboukris** [comment]
Another thought for async calls, perhaps in the second invocation we could return a promise and wait on the original call to complete. There would still be a bottleneck in the module entry point, but the javascript code could be written in a native manner.

**Comment by Ghabry** [comment]
Okay I get it that returning a promise makes sense here to avoid a race condition.

Though then the problem is still that the Promise that is returned by my ``api.downloadSavegame`` never fires. So e.g. ``api.downloadSavegame.then(function() {})`` never invokes the function. Even if I keep emscripten running for 10 seconds.
So I can only make one call.

Is there another missunderstanding about the Api here?

**Comment by RReverser** [comment]
@iboukris Maybe, yeah...

@Ghabry I don't think there's a misunderstanding, the promise should always either resolve or reject, assuming the async operation you have didn't stall. It's hard to tell without a minimal repro.

**Comment by Ghabry** [comment]
okay will try to create a minimal example.
Maybe is also a side effect of using SDL2, will report back later.

**Comment by iboukris** [comment]
@RReverser thing is, given the above we'd have to return a promise for sync calls as well, since there might be async calls in-flight, while this has its drawbacks I think it might still be better.

**Comment by Ghabry** [comment]
@RReverser 

Made a minimal example. It is just a busy loop with a sleep.

Build with

- ``emcmake cmake .``
- ``cmake --build .``

Then launch in your browser and in the dev console invoke ``player.api.downloadSave(1)``.

This will return a pending promise the promise will never finish.

[embind-test.zip](https://github.com/emscripten-core/emscripten/files/8089080/embind-test.zip)

**Comment by RReverser** [comment]
Yes, but is there a way to wait for `main` to actually finish, e.g. by waiting on some Promise like we can in `ccall` or Embind?

**Comment by Ghabry** [comment]
Well my ``main`` function never finishes because it runs the game loop. I want to have the embind stuff invoked while main is sleeping.

I thought this promise stuff is some kind of "cooperative multitasking" here:
When ``main`` calls ``emscripten_sleep`` then main is suspended, so other stuff can run, such as other pending async-calls / promises.

**Comment by RReverser** [comment]
Interesting... I have no idea if that's expected to work tbh.

**Comment by kripken** [comment]
> Yes, but is there a way to wait for main to actually finish, e.g. by waiting on some Promise like we can in ccall or Embind?

Ah, there might not be a promise on the JS side. JS didn't call into main itself, so not sure where that would be placed...

> When main calls emscripten_sleep then main is suspended, so other stuff can run

In general I think we allow simple things to happen while sleeping. For example, a network fetch could call into `malloc()` to write the data it received. It's possible the ccall assertion is too strict for this, however, which is what my patch from earlier might help with, if we think that's the way to go.

But we don't intend other async things to happen - that is the point of the "only one in flight" error. It's very tricky to handle that case properly, which requires handling the C stack as well. Instead, see the [Fibers API](https://emscripten.org/docs/api_reference/fiber.h.html) which is designed for that use case (fibers have a clear definition of how the C stack works etc.).

**Comment by Ghabry** [comment]
Thanks for all the quick help 
I will see if fibers help me.
As this is "not a bug" I'm closing this issue
